# Generated by Django 3.0.3 on 2020-02-21 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in-queue', 'in-queue'), ('in-progress', 'in-progress'), ('completed', 'completed')], default='in-queue', max_length=255)),
                ('name', models.CharField(choices=[('print_something', 'print_something'), ('raise_exception', 'raise_exception'), ('save_foo_object', 'save_foo_object'), ('sleep', 'sleep')], max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
