# Generated by Django 3.0.3 on 2020-02-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_setup_task_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='exception',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in-queue', 'in-queue'), ('in-progress', 'in-progress'), ('completed', 'completed'), ('failed', 'failed')], default='in-queue', max_length=255),
        ),
    ]
