# Generated by Django 3.0.3 on 2020-02-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_exception_field_to_task_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='worker_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(choices=[('long_task', 'long_task'), ('print_something', 'print_something'), ('raise_exception', 'raise_exception'), ('save_foo_object', 'save_foo_object'), ('sleep', 'sleep')], max_length=255),
        ),
    ]
